import compose.icons.AllIcons
import compose.icons.FontAwesomeIcons
import compose.icons.fontawesomeicons.Brands
import compose.icons.fontawesomeicons.brands.FontAwesomeAlt

class FontAwesome {
    companion object : IconPack {
        override val name: String = FontAwesomeIcons::class.simpleName!!
        private val regular = Regular::class.simpleName + "." to Regular.entries
        private val brands = Brands::class.simpleName + "." to Brands.entries
        private val solid = Solid::class.simpleName + "." to Solid.entries
        override val packs = mapOf(regular, brands, solid)
        override val icons = FontAwesomeIcons.AllIcons
        override val icon = FontAwesomeIcons.Brands.FontAwesomeAlt
    }

    enum class Regular {
        PlayCircle, Dizzy, MehBlank, Grin, FileArchive, GrinTongueSquint, KissBeam,
        HandPeace, FileCode, Angry, ThumbsDown, CommentDots, Hdd, Snowflake, FileAlt, HandPaper,
        LaughSquint, Circle, HandLizard, GrinHearts, GrinSquintTears, Registered, Lemon, BellSlash,
        FileWord, CaretSquareUp, Moon, ChartBar, Clock, FileImage, ArrowAltCircleUp, GrinWink,
        WindowClose, StopCircle, HandPointUp, QuestionCircle, CheckSquare, CalendarCheck, Flag,
        ObjectUngroup, WindowMinimize, Clone, Envelope, FilePowerpoint, Edit, LifeRing, Comments,
        CaretSquareLeft, HandRock, Handshake, CommentAlt, Eye, Images, Sun, GrinTears, HandScissors,
        EyeSlash, SadCry, LaughWink, AddressCard, MinusSquare, SmileBeam, MoneyBillAlt, ShareSquare,
        ObjectGroup, KissWinkHeart, GrinTongue, DotCircle, Image, Frown, PauseCircle, Clipboard,
        File, GrinStars, Hourglass, Building, EnvelopeOpen, ClosedCaptioning, UserCircle,
        CalendarMinus, AddressBook, Smile, Save, HandPointDown, Copyright, MehRollingEyes, SadTear,
        PlusSquare, Copy, GrinAlt, ArrowAltCircleDown, Grimace, Futbol, HandSpock, Calendar,
        ListAlt, FilePdf, Lightbulb, FolderOpen, IdCard, FontAwesomeLogoFull, SmileWink, Folder,
        Bookmark, Hospital, Comment, Kiss, StickyNote, Meh, StarHalf, ArrowAltCircleRight,
        PaperPlane, CaretSquareDown, CalendarAlt, Keyboard, ArrowAltCircleLeft, Laugh, FileAudio,
        Map, Square, CalendarPlus, Star, WindowRestore, GrinBeam, WindowMaximize, FileExcel,
        CheckCircle, FrownOpen, CaretSquareRight, HandPointer, Tired, ThumbsUp, Compass,
        TimesCircle, GrinBeamSweat, HandPointLeft, FileVideo, Gem, LaughBeam, CreditCard,
        HandPointRight, Surprise, Newspaper, CalendarTimes, Flushed, IdBadge, Heart, Bell, TrashAlt,
        GrinTongueWink, GrinSquint, User
    }

    enum class Brands {
        WordpressSimple, Buffer, Cloudsmith, Viadeo, StackOverflow, Innosoft, Python,
        Dochub, Wodu, Ember, Discord, YoutubeSquare, Odnoklassniki, Deskpro, CreativeCommonsNd,
        Sellsy, Hotjar, Scribd, Mandalorian, Microblog, GoogleDrive, Skype, Digg, Jenkins, Osi,
        Tumblr, Bitcoin, FacebookSquare, FirstOrderAlt, Shopware, Artstation, FacebookF, GgCircle,
        CcDiscover, Studiovinari, Dropbox, Airbnb, Megaport, Affiliatetheme, Hackerrank, Sass,
        Wpressr, JediOrder, HackerNewsSquare, GitAlt, Superpowers, Squarespace, BattleNet,
        Microsoft, GooglePlusSquare, ViadeoSquare, CcPaypal, SpeakerDeck, Atlassian, Reacteurope,
        YandexInternational, Amazon, Deezer, BuyNLarge, Dev, VimeoSquare, SlackHash,
        FacebookMessenger, Earlybirds, Npm, Asymmetrik, Leanpub, Mastodon, CcAmex, Researchgate,
        Forumbee, Xbox, Quora, Mixer, DAndD, Gitlab, Spotify, Etsy, HackerNews, Weixin, Imdb,
        PinterestP, Ioxhost, Phabricator, OdnoklassnikiSquare, Rev, Ebay, Searchengin, Btc, Opera,
        Wpbeginner, Sith, FreeCodeCamp, Simplybuilt, TumblrSquare, Edge, WatchmanMonitoring,
        Firefox, VimeoV, Amilia, Sourcetree, DribbbleSquare, Mizuni, Vine, Houzz, Usb, Laravel,
        FontAwesomeFlag, Ubuntu, Deviantart, Dyalog, Weibo, ProductHunt, WolfPackBattalion, Supple,
        Themeco, JsSquare, Teamspeak, Css3, Gitkraken, Neos, Unsplash, Reddit, Intercom, Yandex,
        Gitter, Wpforms, Perbyte, InstagramSquare, Google, GetPocket, Rocketchat, StackExchange,
        Bootstrap, Gulp, SnapchatGhost, Mdb, Grunt, Stumbleupon, OptinMonster, Guilded,
        CriticalRole, Expeditedssl, Hubspot, Blackberry, MediumM, Symfony, CcJcb, CreativeCommonsPd,
        Evernote, BehanceSquare, CcMastercard, Accusoft, Envira, Soundcloud, Invision, Codepen,
        Uber, Uncharted, WikipediaW, GitSquare, TencentWeibo, Yoast, Line, Snapchat, LastfmSquare,
        Rust, Mix, Erlang, Adversal, Ns8, AccessibleIcon, Themeisle, Speakap, PiedPiperSquare,
        Sellcast, Dribbble, Yarn, GooglePlay, XingSquare, Empire, AmazonPay, Mixcloud, GlideG,
        Swift, ApplePay, LinkedinIn, GithubSquare, Periscope, FortAwesomeAlt, Discourse,
        Nutritionix, Css3Alt, GithubAlt, Draft2digital, Viber, Kickstarter, Meetup, Whatsapp,
        Palfed, Ussunnah, CottonBureau, Aws, RedditAlien, GalacticSenate, RProject,
        CreativeCommonsPdAlt, Cpanel, Windows, Bitbucket, Zhihu, Suse, Angrycreative, CcAmazonPay,
        PhoenixSquadron, Php, Whmcs, Monero, Keybase, Salesforce, Lastfm, Patreon, DigitalOcean,
        RaspberryPi, TradeFederation, Fulcrum, Orcid, CreativeCommonsZero, Servicestack, Diaspora,
        Android, Grav, Openid, Java, Slideshare, Waze, Schlix, CcDinersClub, TelegramPlane, Lyft,
        Medium, Glide, Telegram, Apper, FortAwesome, SteamSquare, GooglePlus, Goodreads, Nimblr,
        DAndDBeyond, Quinscape, Untappd, PennyArcade, Hips, Fly, Html5, Steam, Vimeo, AppStore,
        Weebly, Cloudscale, Foursquare, Slack, Freebsd, Dailymotion, Buysellads, Jsfiddle, Ravelry,
        Renren, GooglePay, Paypal, Firstdraft, NodeJs, Fonticons, Typo3, Replyd,
        CreativeCommonsNcEu, Staylinked, Uniregistry, PinterestSquare, Itunes, CcVisa, Yelp,
        CreativeCommonsSa, FantasyFlightGames, SteamSymbol, Angular, Linux, Umbraco, FontAwesome,
        FontAwesomeLogoFull, Drupal, PiedPiperPp, Apple, Deploydog, Trello, Vk, PiedPiperAlt, React,
        Linkedin, Gg, Bluetooth, Fedora, Twitter, Adn, FirstOrder, Pinterest, Audible, EdgeLegacy,
        Vuejs, Cloudversify, Ideal, Hornbill, Cuttlefish, Hive, CreativeCommons, Bity, BluetoothB,
        Medrt, Jira, Resolving, Instalod, CreativeCommonsSamplingPlus, Bimobject, RedRiver, Ups,
        Pagelines, Safari, Figma, Medapps, CreativeCommonsNc, Node, Youtube, Mendeley, Modx,
        InternetExplorer, FonticonsFi, Dhl, Viacoin, Readme, CreativeCommonsSampling, _500px,
        Opencart, CanadianMapleLeaf, CreativeCommonsBy, AcquisitionsIncorporated, BloggerB, Flickr,
        Twitch, Blogger, Skyatlas, Maxcdn, Rebel, GoodreadsG, Keycdn, Pushed, Centercode, Yammer,
        Facebook, Shopify, Autoprefixer, Stackpath, Aviato, RedditSquare, CcApplePay, Fedex,
        Tripadvisor, PiedPiper, Centos, Qq, Docker, Vaadin, FirefoxBrowser, SnapchatSquare, Js,
        Bandcamp, TheRedYeti, Playstation, GoogleWallet, Yahoo, CreativeCommonsRemix, GooglePlusG,
        WhatsappSquare, StumbleuponCircle, BlackTie, Vnv, OctopusDeploy, Codiepie, Behance, Sketch,
        Joget, Contao, Usps, ItunesNote, Shirtsinbulk, CreativeCommonsShare, WizardsOfTheCoast,
        Kaggle, TwitterSquare, Page4, Chrome, Stripe, Instagram, Linode, Wordpress, HireAHelper,
        CcStripe, GalacticRepublic, Angellist, ThinkPeaks, Wix, Joomla, StripeS, Wpexplorer,
        Elementor, Uikit, Confluence, Gratipay, CreativeCommonsNcJp, Strava, YCombinator,
        FontAwesomeAlt, PiedPiperHat, Algolia, Napster, Chromecast, ItchIo, Dashcube,
        Buromobelexperte, Git, Magento, Less, KickstarterK, Ethereum, PhoenixFramework, Rockrms,
        Korvue, Github, Gofore, Xing, Ello, OldRepublic, Redhat, Sistrix, Delicious, StickerMule,
        Unity, Hooli, Gripfire, Mailchimp, Alipay, Avianex, Cloudflare, AppStoreIos, Tiktok,
        Markdown, Connectdevelop, Flipboard
    }

    enum class Solid {
        CalendarDay, GreaterThanEqual, ToggleOn, PlayCircle, HatWizard, Dizzy, Car,
        LuggageCart, LongArrowAltLeft, UserCheck, AlignLeft, CommentSlash, Train, Columns,
        Wheelchair, MehBlank, ShippingFast, Underline, BlenderPhone, TachometerAlt, MobileAlt,
        Biohazard, Pause, Stamp, Tablet, Headset, CaretLeft, Font, Transgender, Cubes, Grin,
        BaseballBall, VolumeMute, Camera, FileArchive, ThermometerThreeQuarters, Snowman,
        CloudUploadAlt, CarCrash, Swatchbook, BatteryQuarter, CloudSun, EllipsisH, FileDownload,
        LessThan, DoorOpen, GrinTongueSquint, UserInjured, PrescriptionBottleAlt, Atlas, Smog,
        Percent, Donate, SpaceShuttle, TruckMoving, Heartbeat, StreetView, KissBeam, DrumstickBite,
        Pager, FighterJet, LaptopCode, Plus, QuoteLeft, CookieBite, Synagogue, SolarPanel, GolfBall,
        Minus, SortAmountDown, Play, Kaaba, AppleAlt, Trademark, StoreAlt, Socks, HandshakeSlash,
        Percentage, UserNurse, Backspace, Upload, AngleDown, Plane, SearchPlus, ProjectDiagram,
        UserSecret, Medkit, GripLines, Hryvnia, SearchDollar, ShoePrints, TableTennis, EllipsisV,
        Divide, DiceD6, PenSquare, Paragraph, HandPeace, AngleUp, PrayingHands, SatelliteDish, Cube,
        Warehouse, Hands, TrashRestoreAlt, Hotel, Gavel, HardHat, CloudMoon, StoreAltSlash,
        FileCode, Ankh, Angry, SpellCheck, Dungeon, CalendarWeek, ThumbsDown, PaintBrush,
        DrawPolygon, Mitten, GasPump, PhoneSquareAlt, SortNumericDownAlt, Snowboarding, Cogs,
        BirthdayCake, ChessRook, PlusCircle, Glasses, CommentDots, Box, Memory, BriefcaseMedical,
        Highlighter, GripVertical, Hdd, Snowflake, UsersSlash, ArrowUp, CommentMedical,
        SortAlphaUpAlt, PlaneDeparture, VectorSquare, MicrophoneAltSlash, Child, PooStorm,
        MicrophoneAlt, FileAlt, HandPaper, LaughSquint, RulerHorizontal, DraftingCompass, Circle,
        ArrowsAltV, HandLizard, Podcast, Restroom, EuroSign, BookReader, ChevronDown, CashRegister,
        Tools, BoxTissue, Truck, CameraRetro, GrinHearts, ArrowCircleLeft, Code, GrinSquintTears,
        ChartArea, Cog, Thumbtack, Dragon, UserTimes, Registered, Palette, Ruler, TrashRestore,
        ThermometerHalf, History, VolumeDown, PowerOff, PhoneAlt, Lemon, BellSlash, Home, Bacon,
        FillDrip, FileWord, Stethoscope, InfoCircle, WonSign, MousePointer, CaretSquareUp, Tint,
        CloudDownloadAlt, Walking, Quidditch, ChartPie, Backward, Tasks, RedoAlt, Wrench, Database,
        Gopuram, Ribbon, Pray, Biking, Moon, FileSignature, ExclamationTriangle, ChartBar, Wallet,
        HourglassEnd, Clock, FunnelDollar, Igloo, UserAlt, Sort, UserMinus, ChessQueen, BowlingBall,
        Parking, Bed, HeadSideVirus, FileImage, Dog, PencilAlt, Heading, XRay, Signature, Marker,
        Hanukiah, ArrowAltCircleUp, GrinWink, HollyBerry, Tablets, CommentDollar, HorseHead, Paw,
        Ban, Ring, Spinner, WindowClose, University, Crown, SmokingBan, Bacterium, Ad, TruckPickup,
        Mars, Hotdog, WaveSquare, Award, ExchangeAlt, Blender, FileUpload, AlignCenter,
        ParachuteBox, HatCowboy, CartArrowDown, StopCircle, Paste, Chalkboard, PenFancy, Slash,
        Ambulance, Guitar, StepForward, Desktop, ToiletPaperSlash, DiceD20, HandPointUp,
        QuestionCircle, CheckSquare, Retweet, Directions, TextWidth, ExpandArrowsAlt, GlobeAfrica,
        SignInAlt, List, TextHeight, Phone, CalendarCheck, Route, Users, Anchor, Flag, Trophy,
        BreadSlice, Italic, GlobeAmericas, StepBackward, ObjectUngroup, NotesMedical,
        WindowMinimize, GraduationCap, SortNumericDown, Clone, LowVision, AlignJustify, Om, Bug,
        Terminal, UndoAlt, Helicopter, UserShield, Envelope, Suitcase, DiceThree,
        ThermometerQuarter, FilePowerpoint, BookMedical, Ethernet, CompressArrowsAlt, Edit,
        PizzaSlice, TrafficLight, Boxes, UserPlus, GripLinesVertical, Crosshairs, ArrowCircleUp,
        ToiletPaper, LifeRing, NotEqual, VirusSlash, Comments, CaretSquareLeft, MailBulk, BorderAll,
        ArrowLeft, ChessBishop, BatteryHalf, StarOfDavid, DollarSign, HandRock, Handshake, Plug,
        Menorah, BoxOpen, CloudMeatball, ShoppingBag, ChessPawn, ShareAlt, ArrowDown, Skull, Film,
        ClipboardCheck, WineBottle, Republican, IdCardAlt, ListUl, SortAmountUpAlt, CommentAlt,
        Frog, Stream, LevelDownAlt, Eye, Recycle, Voicemail, Egg, TemperatureHigh, Briefcase,
        Skiing, WineGlassAlt, Images, Capsules, Superscript, BusAlt, RupeeSign, Broom, Sun,
        CloudMoonRain, EnvelopeSquare, LiraSign, GrinTears, Seedling, UsersCog, CarBattery,
        ArrowCircleRight, Virus, FireAlt, HandScissors, FistRaised, RemoveFormat, Tram,
        SearchLocation, EyeSlash, ArrowsAlt, SadCry, AngleRight, Video, Strikethrough, Mobile,
        FileExport, Neuter, LaughWink, BalanceScaleRight, FolderMinus, Cross, Screwdriver,
        AssistiveListeningSystems, FileMedicalAlt, FastForward, BatteryFull, MarsDouble, Rainbow,
        Bible, MinusCircle, DumpsterFire, Unlock, HouseDamage, Sign, AngleDoubleDown, Peace,
        AirFreshener, Hammer, DrumSteelpan, Rocket, MugHot, Bomb, Spa, AddressCard,
        LongArrowAltRight, MinusSquare, BorderStyle, MoneyBillWaveAlt, TeethOpen, PeopleCarry,
        Subscript, PenNib, VrCardboard, MortarPestle, ListOl, SmileBeam, Undo, MoneyBillAlt, Taxi,
        Leaf, ShareSquare, Quran, ObjectGroup, Medal, KissWinkHeart, HandHoldingHeart, GrinTongue,
        CompactDisc, Fingerprint, Paperclip, DotCircle, Jedi, FileMedical, Image, Road, UserSlash,
        VolumeUp, Crop, HandHoldingUsd, UserCog, LessThanEqual, BezierCurve, Horse,
        FileInvoiceDollar, Female, GlassMartini, JournalWhills, StoreSlash, Water, Icicles,
        AngleLeft, SquareRootAlt, Binoculars, PuzzlePiece, Mosque, UmbrellaBeach, Dharmachakra,
        SprayCan, HeadphonesAlt, DollyFlatbed, Cut, Frown, Campground, PauseCircle, Tag, HotTub,
        UserGraduate, CircleNotch, HandHoldingMedical, Cookie, SimCard,
        AmericanSignLanguageInterpreting, ThermometerEmpty, Clipboard, Sitemap, Baby, RssSquare,
        File, Reply, HouseUser, CloudSunRain, GrinStars, Stop, ToggleOff, FastBackward, ShieldAlt,
        HatCowboySide, Bicycle, UserMd, Hourglass, SignOutAlt, Book, Spider, ChevronCircleUp,
        Building, YenSign, Magic, HSquare, EnvelopeOpen, Ship, HeartBroken, ClosedCaptioning, Icons,
        Archway, Motorcycle, UserCircle, GlobeAsia, Prescription, CalendarMinus, RulerCombined,
        Sink, Check, Globe, Signal, ChevronCircleRight, MarsStrokeH, Server, HeadSideMask,
        Microscope, Chair, MoneyBillWave, AddressBook, Smile, AngleDoubleLeft, MoneyBill, Bone,
        StarOfLife, ExpandAlt, Infinity, PlaneArrival, ChevronUp, UserAstronaut, Drum, Carrot,
        SearchMinus, RubleSign, Adjust, Industry, Save, Rss, Asterisk, TransgenderAlt, Skating,
        UserNinja, BroadcastTower, UtensilSpoon, ClinicMedical, HandPointDown, Venus, Sync,
        HospitalUser, Bacteria, AlignRight, Copyright, ExternalLinkAlt, Smoking, MehRollingEyes,
        Microphone, TheaterMasks, SignLanguage, Bus, FilePrescription, Tractor, Teeth, PlaneSlash,
        Pallet, HandsHelping, Atom, SadTear, Brain, ChartLine, Question, PlusSquare, ArrowsAltH,
        Weight, WeightHanging, Monument, TintSlash, Eject, Copy, OilCan, Wind, Vial, Cheese,
        GrinAlt, Diagnoses, ArrowAltCircleDown, Laptop, PrescriptionBottle, ThLarge, Grimace,
        UserAltSlash, HospitalSymbol, Pills, Otter, Exclamation, Vihara, CaretDown, Hippo, Futbol,
        Indent, CartPlus, IceCream, Gift, GlobeEurope, YinYang, LungsVirus, HandSpock, Forward,
        HeadSideCoughSlash, Calendar, ListAlt, Poo, FilePdf, FireExtinguisher, Lightbulb, Tenge,
        Utensils, LockOpen, SortAlphaDownAlt, Music, SquareFull, FolderOpen, Cannabis,
        BatteryThreeQuarters, Tshirt, MapSigns, Thermometer, IdCard, FontAwesomeLogoFull,
        Stroopwafel, HandSparkles, SmileWink, BasketballBall, Poll, SuitcaseRolling, Filter,
        MapMarkedAlt, Procedures, ShoppingBasket, Toolbox, ShuttleVan, MapMarked, Search, Folder,
        Braille, Equals, ICursor, Expand, PepperHot, Bars, CandyCane, Bookmark, Passport,
        HandHoldingWater, Khanda, Bullseye, Dna, Fish, MarsStrokeV, Soap, Blind, Trash,
        SkullCrossbones, ShieldVirus, Hospital, CaretRight, GlassCheers, Umbrella, Magnet, Key,
        FlagUsa, Certificate, ChargingStation, VoteYea, Comment, TicketAlt, KiwiBird, UserTag, Tty,
        WineGlass, BatteryEmpty, ShareAltSquare, Scroll, LongArrowAltUp, ArrowRight, MarsStroke,
        Wifi, SortDown, Kiss, Satellite, StickyNote, Headphones, Beer, CodeBranch, RecordVinyl,
        HospitalAlt, FlagCheckered, Dove, Shower, Meh, StarHalf, Ghost, City, Calculator,
        SortAlphaUp, ArrowAltCircleRight, ChessBoard, Dolly, PaperPlane, CaretSquareDown, PenAlt,
        Download, ArrowCircleDown, Mountain, ExclamationCircle, School, Cat, GlassWhiskey, Language,
        Link, Store, VestPatches, CalendarAlt, Keyboard, HeadSideCough, PaintRoller,
        ArrowAltCircleLeft, Stopwatch, TruckLoading, PhoneVolume, Info, Subway, VenusMars, Receipt,
        Laugh, Fill, VolumeOff, Vest, FileAudio, PhotoVideo, Bong, PoundSign, Map, MoneyCheck,
        FeatherAlt, Square, BorderNone, CloudShowersHeavy, Print, Sleigh, ThList, Mouse, Unlink,
        Crutch, SortAlphaDown, Pastafarianism, Dice, Church, BandAid, EyeDropper, Hiking, Running,
        Flask, CommentsDollar, Portrait, Radiation, Outdent, Redo, CalendarPlus, BookOpen,
        MapMarker, Star, BusinessTime, MapMarkerAlt, FileImport, WindowRestore, Sms, GrinBeam,
        WindowMaximize, UserLock, Coffee, ConciergeBell, ChevronLeft, Tv, HandMiddleFinger, Gifts,
        PlaceOfWorship, FileExcel, GlassMartiniAlt, CheckCircle, FrownOpen, At, MicrophoneSlash,
        CaretSquareRight, ChevronCircleDown, Torah, Hamburger, CompressAlt, Inbox, FolderPlus,
        Faucet, Fire, HandPointer, Meteor, UserEdit, UniversalAccess, Lock, HandHolding, Cocktail,
        Feather, SwimmingPool, PhoneSlash, Tired, SortAmountUp, Share, PiggyBank, ThumbsUp,
        PhoneSquare, MapPin, LongArrowAltDown, PumpSoap, Democrat, Fax, Landmark, SortUp, Trailer,
        Tooth, Hamsa, GreaterThan, Compass, CaretUp, Bolt, Deaf, Caravan, Viruses, TimesCircle,
        LaptopMedical, LocationArrow, HandsWash, Genderless, CarAlt, Syringe, Blog, GrinBeamSweat,
        AudioDescription, FileInvoice, BalanceScaleLeft, Tags, ChessKing, SortNumericUpAlt,
        HandPointLeft, Tree, ThermometerFull, MoneyCheckAlt, FileVideo, SortNumericUp, Bath, Eraser,
        HandshakeAltSlash, Tape, RadiationAlt, Bahai, LayerGroup, CheckDouble, LevelUpAlt, Barcode,
        Shapes, Gem, Pen, ShekelSign, ExternalLinkSquareAlt, AngleDoubleRight, Dumbbell, CloudRain,
        TemperatureLow, SkiingNordic, Vials, ClipboardList, Microchip, Stopwatch20, PumpMedical,
        Splotch, FirstAid, Compress, LaughBeam, Qrcode, UnlockAlt, ShoppingCart, Bullhorn,
        ChessKnight, PersonBooth, Times, CreditCard, TruckMonster, Coins, HandPointRight, Archive,
        Bold, UserFriends, Surprise, DiceOne, Disease, ChalkboardTeacher, Lungs, TabletAlt, UserTie,
        Th, Toilet, VolleyballBall, ToriiGate, PeopleArrows, StarAndCrescent, RulerVertical,
        QuoteRight, CropAlt, Male, SyncAlt, DiceTwo, Newspaper, Gamepad, SdCard, ReplyAll, FileCsv,
        LaptopHouse, CalendarTimes, VideoSlash, DiceFive, Couch, DiceFour, Flushed, IdBadge, Random,
        Fan, Allergies, FileContract, FootballBall, ChevronRight, CarSide, HourglassStart,
        EnvelopeOpenText, Snowplow, Crow, NetworkWired, AngleDoubleUp, Poop, BalanceScale, Heart,
        DoorClosed, Chess, Bell, TrashAlt, PencilRuler, Burn, StarHalfAlt, Robot, Mercury, BookDead,
        PollH, UserClock, GrinTongueWink, HourglassHalf, BabyCarriage, Hashtag, Brush,
        ChevronCircleLeft, SlidersH, GripHorizontal, HockeyPuck, GrinSquint, Dumpster, DiceSix,
        Cloud, DigitalTachograph, Joint, SortAmountDownAlt, VenusDouble, Table, Swimmer, User, Mask
    }

}