package packs

import compose.icons.AllIcons
import compose.icons.CssGgIcons
import compose.icons.cssggicons.Bot

class CssGg {
    companion object : IconPack {
        override val name: String = CssGgIcons::class.simpleName!!
        private val all = "" to Icons.entries
        override val packs = mapOf(all)
        override val icons = CssGgIcons.AllIcons
        override val icon = CssGgIcons.Bot
    }

    enum class Icons {
        EditStraight, SoftwareDownload, ToggleOn, MailOpen, ArrowDownO,
        PentagonTopRight, Duplicate, Template, More, AlignLeft, PathBack, ArrowLongLeft, Bee,
        LivePhoto, Oculus, DetailsMore, PlayTrackPrevO, MenuGridR, CardHearts, Ratio, Headset,
        Style, DistributeVertical, ArrowsScrollV, Brackets, MoreO, Swiss, ArrowLongUpC,
        ArrowsMergeAltV, ArrowTopLeftR, ArrowsScrollH, PlayListCheck, Camera, ArrowLongLeftL,
        ArrowLongUpR, PentagonBottomLeft, PentagonRight, GenderFemale, MinimizeAlt, Album,
        LayoutPin, CalendarDates, ViewDay, FormatBold, DisplaySpacing, Serverless, Filters, Studio,
        FormatColor, Dice4, Shutterstock, SortZa, Backspace, EditExposure, PlayForwards, MoveUp,
        DisplayFlex, ArrowLongDownR, PlayListAdd, GitCommit, Tally, Ereader, AppleWatch,
        IndieHackers, ShapeCircle, ArrowsExpandLeft, GitFork, PlayStop, EditNoise, GitBranch,
        Abstract, BorderTop, FormatCenter, SelectO, CornerDownLeft, Microsoft, Bot, QuoteO,
        Performance, HomeAlt, CornerUpRight, MenuLeftAlt, PathCrop, ArrowLongLeftE, Photoscan,
        PinAlt, PathDivide, Maximize, ArrowBottomRightO, ArrowsExchangeAltV, Box, ArrowLeftR, Tab,
        FormatJustify, GoogleTasks, ChevronDoubleDown, ArrowUp, Add, Airplane, SmileNeutral,
        DarkMode, BorderStyleSolid, Euro, ZoomOut, Alarm, MoreVertical, Npm, PushChevronDown,
        ToggleSquare, ZoomIn, EyeAlt, Transcript, Inpicture, ChevronDown, HomeScreen, Bowl, Code,
        ChevronUpR, CornerRightUp, Digitalocean, DockLeft, Timer, Stories, PlayTrackNextR, LogOut,
        ChevronDoubleDownO, Ruler, EditUnmask, SmartHomeBoiler, SmartHomeCooker, ArrowLongLeftR,
        ChevronDoubleUp, MenuHotdog, Home, MoveRight, ArrowUpR, FormatItalic, PlayTrackPrev,
        SpaceBetweenV, Enter, ArrowsShrinkV, MusicNote, ClapperBoard, CalendarToday, Database,
        MediaLive, PushChevronUp, Printer, Moon, Crowdfire, Stack, SandClock, WorkAlt, PinTop,
        ArrowLongUpE, PushChevronLeftR, InsertAfter, Attachment, MusicSpeaker, GitPull,
        ArrowsBreakeV, RemoveR, MathDivide, Usb, ArrowTopRightR, ChevronRightO, SidebarOpen,
        SmartHomeWashMachine, ArrowsShrinkH, PlayList, ArrowsExpandRight, PlayListRemove,
        ArrowRightR, DetailsLess, PushRight, PlayStopO, Ring, ArrowsExpandDownLeft, ArrowLongUpL,
        Spinner, Shield, Dice1, Crown, ScreenWide, ProductHunt, PathFront, Block, MoveLeft,
        PlayTrackNextO, ViewCols, AlignCenter, Notifications, VoicemailO, MoveDown, MenuLeft, LogIn,
        Pexels, CPlusPlus, Desktop, ShapeHexagon, Controller, ArrowsVAlt, ArrowLongUp, Sidebar,
        CodeSlash, Webcam, CornerDoubleUpLeft, Drive, Unsplash, Presentation, Glass, PlayPauseR,
        FormatHeading, DistributeHorizontal, List, Gitter, Phone, MiniPlayer, Anchor, Flag, Trophy,
        Dice2, Pokemon, Eventbrite, Google, PentagonLeft, AlignMiddle, LayoutGrid, SmartphoneRam,
        AlignBottom, DockWindow, MoreVerticalO, Extension, Linear, CornerDownRight, Terminal,
        ArrowTopLeftO, Spectrum, MoreR, ToolbarTop, InsertBefore, Captions, BorderStyleDashed,
        ChevronUpO, ChevronDoubleUpO, ToolbarBottom, Maze, CornerDoubleLeftDown, Smartphone, CloseR,
        Ethernet, ArrowsExpandUpRight, ArrowTopRight, MenuMotion, FlagAlt, Sweden, Twilio,
        BorderAll, ArrowLeft, SmartHomeHeat, PushChevronLeft, Unfold, ArrowBottomLeftO, Plug,
        FormatUppercase, Girl, Disc, ShoppingBag, SpinnerTwo, TrashEmpty, ArrowDown, Microbit,
        PentagonBottomRight, Film, EditMarkup, Stark, PushChevronRightR, Adidas, Polaroid, MenuCake,
        Eye, ArrangeFront, Voicemail, Briefcase, UserRemove, EditContrast, CardClubs, InsertBeforeO,
        MenuCheese, Qr, Scan, Chart, ArrowsMergeAltH, Tikcode, Sun, Support, FormatText, ScreenShot,
        Size, Loadbar, SmileNone, PushChevronLeftO, SelectR, Battery, CornerRightDown, Select,
        FileAdd, SortAz, Insights, CalendarDue, Dribbble, Assign, CheckR, SmartphoneChip, Cross,
        Userlane, ArrowsExpandLeftAlt, BatteryFull, PlayButtonO, SmartphoneShake, Attribution,
        Components, SmileNoMouth, Read, Dialpad, ViewSplit, Close, Boy, AddR, LockUnlock,
        CornerDoubleRightDown, ArrowLongRightL, Undo, MenuOreos, PlayPause, Menu, PlayTrackNext,
        DropInvert, ArrowTopLeft, CornerLeftUp, PushChevronDownO, MailReply, Icecream,
        MergeHorizontal, ViewMonth, ArrowsV, Image, Windows, Bitbucket, Crop, SearchLoading, Volume,
        Quote, Reorder, ComedyCentral, SpaceBetween, SoftwareUpload, Nametag, BorderRight,
        PlayButtonR, MoreAlt, CalendarTwo, ChevronDoubleDownR, Thermostat, Tag, ChevronLeftR,
        BorderLeft, ArrowLeftO, ShapeRhombus, Clipboard, Patreon, Carousel, PlayBackwards,
        SpinnerAlt, File, ArrowsHAlt, PlayListSearch, DropOpacity, Tennis, ToggleOff, Website,
        MergeVertical, Screen, MoveTask, EditFlipV, MenuRight, ShapeHalfCircle, Feed, MenuRound,
        ChevronDoubleLeftO, Designmodo, Debug, OpenCollective, ShapeSquare, CardDiamonds, Export,
        PushChevronUpR, MenuRightAlt, ArrowsH, Check, Globe, ArrowLongDownE, Signal, LogOff,
        ExtensionRemove, Server, VoicemailR, Chanel, Organisation, Smile, Overflow, PlayTrackPrevR,
        MenuGridO, ChevronRightR, CheckO, Infinity, CardSpades, GenderMale, PathTrim, ChevronUp,
        PathIntersect, Vinyl, UserAdd, Trending, Browse, Shortcut, DockRight, FolderRemove,
        RadioChecked, ColorPicker, Asterisk, Ericsson, ChevronDownR, Options, Slack, Yinyang, Sync,
        Hello, FormatUnderline, RowFirst, FormatLeft, RadioCheck, AlignRight, Copyright,
        FormatSlash, IfDesign, Remove, CompressRight, Time, Paypal, Dice5, BorderBottom, MathPlus,
        Circleci, Piano, LoadbarDoc, Eject, PushDown, Copy, PlayPauseO, PathUnite, EditFade, Laptop,
        ArrowsBreakeH, ChevronDoubleUpR, GlobeAlt, ArrowLongDownL, Gift, Pacman, Calendar,
        PlayStopR, GhostCharacter, EditFlipH, ArrowRightO, Unblock, MenuBoxed, Music, Calibrate,
        SearchFound, SidebarRight, Framer, PathExclude, ArrowAlignV, Thermometer, ArrowDownR,
        EditBlackPoint, Poll, Trello, Profile, ShapeZigzag, Toolbox, ArrowsExchangeAlt, Search,
        Folder, Lastpass, CompressLeft, Password, CornerDoubleUpRight, Expand, CloseO, Bookmark,
        ChevronDoubleRight, Twitter, CornerDoubleDownLeft, Collage, ChevronLeftO, Trash, Umbrella,
        Erase, Magnet, Key, EditShadows, Comment, CalendarNext, BatteryEmpty, SpinnerTwoAlt,
        ArrowRight, DisplayGrid, ChevronDoubleRightO, ArrowsExpandUpLeft, AlignTop, PentagonUp,
        ShapeTriangle, Bmw, ArrowLongRightE, FontHeight, InsertBeforeR, PentagonTopLeft, Figma,
        Zeit, FormatIndentIncrease, Ghost, Calculator, Swap, Youtube, Track, Dollar, SmileUpside,
        ArrowsExchange, Atlasian, ExtensionAlt, PushChevronUpO, Dolby, Readme, RowLast, MathEqual,
        Link, MediaPodcast, FormatIndentDecrease, ArrowsExpandDownRight, Keyboard, ArrowLongRightC,
        Stopwatch, SmileSad, ViewGrid, Info, PushUp, Today, ViewComfortable, MoreVerticalAlt,
        TapSingle, Notes, EditMask, ArrowLongLeftC, ArrangeBack, Facebook, Square, MathMinus, Mouse,
        Gym, UiKit, SmartHomeRefrigerator, SwapVertical, FileDocument, Cap, BandAid, Dice6,
        PinBottom, TrendingDown, PathOutline, ToggleSquareOff, Loupe, CornerUpLeft, External, Sleep,
        Redo, LayoutList, ArrowBottomLeftR, Danger, PushLeft, CornerDoubleDownRight, Touchpad,
        DisplayFullwidth, Games, Coffee, ChevronLeft, FormatSeparator, ArrowLongRight, Tv, Monday,
        Rename, ColorBucket, Inbox, Keyhole, SmartHomeLight, Mail, MoreVerticalR, ArrowAlignH,
        Sketch, Repeat, Lock, Timelapse, Pin, Bulb, Share, FormatLineHeight, ScrollH, MaximizeAlt,
        CornerLeftDown, SmileMouthOpen, ArrowBottomRight, Pill, MailForward, Bolt, CompressV,
        FolderAdd, Community, Instagram, ScreenMirror, ArrowLongDown, ListTree, InsertAfterR, Tree,
        Data, Unavailable, UsbC, Awards, PushChevronRight, ChevronDownO, Pen, PlayButton, Drop,
        TapDouble, PushChevronRightO, Trees, Terrain, LoadbarAlt, DockBottom, Compress, GlassAlt,
        ShoppingCart, ScrollV, CreditCard, ChevronDoubleRightR, Record, Modem, Minimize, ViewList,
        FormatStrike, PullClear, ArrowLongRightR, MathPercent, ChevronDoubleLeft, LayoutGridSmall,
        ToolbarLeft, CornerDoubleRightUp, PentagonDown, Remote, BorderStyleDotted, ArrowUpO,
        ArrowsExpandRightAlt, Pocket, UserList, ArrowsExchangeV, ToolbarRight, ChevronRight,
        Browser, InsertAfterO, Import, Dice3, ExtensionAdd, Heart, Bell, Internal, Mic, FileRemove,
        Cast, ArrowBottomRightR, Board, CodeClimate, FontSpacing, ArrowBottomLeft, Hashtag, Brush,
        PushChevronDownR, ArrowLongDownC, Cloud, FormatRight, EditHighlight, LoadbarSound,
        ArrowTopRightO, ChevronDoubleLeftR, CornerDoubleLeftUp, User
    }
}