package packs

import compose.icons.AllIcons
import compose.icons.SimpleIcons
import compose.icons.simpleicons.Simpleicons

class Simple {
    companion object : IconPack {
        override val name: String = SimpleIcons::class.simpleName!!
        private val all = "" to Icons.entries
        override val packs = mapOf(all)
        override val icons = SimpleIcons.AllIcons
        override val icon = SimpleIcons.Simpleicons
    }

    enum class Icons {
        Livejournal, W3c, Hackthebox, Gimp, Fedramp, Svgo, Nintendoswitch,
        Campaignmonitor, Skoda, Skyliner, Suzuki, Mongodb, Amazonfiretv, Haskell, Delta, Apache,
        Junipernetworks, Buffer, Cloudsmith, Viadeo, Eightsleep, Taxbuzz, Dblp,
        Commonworkflowlanguage, Poly, Appveyor, Trustedshops, Fozzy, Oculus, Microsoftword, Swagger,
        Stackbit, Minutemailer, Wireguard, Max, Kirby, Python, Audi, Citrix, Nvidia, Processwire,
        Apostrophe, Pandora, Freenas, Discord, Playstation3, Scratch, Chainlink, Wolfram, Gnubash,
        Facebookgaming, Cocoapods, Venmo, Rte, Ibm, Rezgo, Canonical, Visa, Odnoklassniki,
        Paritysubstrate, Proxmox, Jitsi, Jamstack, Veepee, Prosieben, Southwestairlines, Qgis, Deno,
        Hellofresh, Themodelsresource, Adblockplus, Qantas, Sourceengine, Here, Prestashop,
        Octopusdeploy, Habr, Starz, Cloudbees, Csswizardry, Drone, Tado, Coinbase, Kodi, Geocaching,
        Americanexpress, Pagseguro, Googleearth, Ferrari, Strongswan, Logmein, Scipy, Dart, Mega,
        Nasa, Hotjar, Gumroad, Steamworks, Mxlinux, Scribd, Graphql, Themoviedatabase, Palantir,
        Contentful, Automatic, Iata, Rabbitmq, Garmin, Iheartradio, Tapas, Minecraft,
        Microsoftacademic, Altiumdesigner, Aiqfome, Deutschebahn, Mastercomfig, Skype, Dtube,
        Okcupid, Trove, Farfetch, Serverless, Lamborghini, Shazam, Digg, Corsair, S7airlines, Nixos,
        Jenkins, Paytm, Myanimelist, Opnsense, Opslevel, KoFi, Smugmug, Datacamp, Favro, Kakaotalk,
        Aliexpress, Shutterstock, Sensu, Pandas, Riseup, Amd, Tumblr, Zingat, Craftcms, Bitcoin,
        Alpinelinux, Jasmine, Mercedes, Ifttt, Sonarcloud, Nx, Blazemeter, Googleads, Veeam,
        Vimeolivestream, Webstorm, Openssl, Sinaweibo, Karlsruherverkehrsverbund, Gitbook, Jeep,
        Jsonwebtokens, Shopware, Trendmicro, Artstation, Leaflet, Googletagmanager, Stellar,
        Microsoftedge, NuxtDotJs, Contactlesspayment, Esea, BattleDotNet, Doordash, Playstationvita,
        BrandDotAi, Labview, Codemirror, Hugo, Cevo, Anaconda, Dropbox, Googleadsense, Revolut, Ktm,
        Airbnb, Googlehangouts, Heroku, Asana, Ios, Hackerrank, Sass, Minetest, Stackexchange,
        Abstract, Namecheap, Jfrogbintray, Happycow, Husqvarna, Nginx, Nintendogamecube,
        Crunchyroll, Haveibeenpwned, Hyperledger, LastDotFm, Ryanair, Prisma, Qiskit, Bower,
        Squarespace, Microsoft, Prime, Rubygems, Artixlinux, Swiper, Figshare, AudioTechnica,
        Devpost, Xamarin, Strapi, Brave, Coronarenderer, Atlassian, Showpad, TripDotCom, Justeat,
        Bloglovin, Mariadb, Scrimba, Numpy, Turkishairlines, Wii, Sparkasse, Box, Sepa,
        Vlcmediaplayer, Vectorworks, Hatenabookmark, Sketchup, Sublimetext, Githubactions, Llvm,
        Worldhealthorganization, Amazon, Sparkpost, Snowflake, Deezer, Openfaas, Askfm, Cakephp,
        Playcanvas, Seagate, Ocaml, Apachecloudstack, Eclipseide, Adobeaftereffects,
        Ethiopianairlines, Duolingo, Microsoftonedrive, PrDotCo, Trino, Primevideo, Npm, Treehouse,
        Filezilla, Gotomeeting, Circle, Tampermonkey, Turbosquid, Apachehive, Linuxcontainers, Jpeg,
        Ndr, Volvo, Actigraph, Leanpub, Mastodon, Veritas, Chrysler, Coda, Crunchbase, Norwegian,
        Spinrilla, Qualcomm, Mediafire, Philipshue, Beijingsubway, Pyup, Floatplane, Capacitor,
        Julia, Pimcore, Linuxfoundation, Toshiba, Hootsuite, Qiita, Haxe, Airfrance, Researchgate,
        Googlemaps, Siemens, Homify, Antena3, Spreaker, Gmail, Openaccess, Semanticuireact,
        Thumbtack, Wearos, Pytorch, Xbox, Transportforireland, Quora, Ulule, Clyp, Digitalocean,
        GovDotUk, Bookmeter, Openvpn, Epson, Ansible, Clojure, Onlyfans, Valve, Weasyl, Darkreader,
        Directus, Googlekeep, Antdesign, Gitlab, Spotify, Speedtest, Etsy, Vim, Jabber, Spacex,
        Chatbot, Teamcity, Chakraui, Opensuse, Walkman, Kubernetes, Dash, Googlesheets, Kyocera,
        Laravelnova, Codewars, Vagrant, Ubisoft, Adobeaudition, Opennebula, Slickpic, Godotengine,
        Mediatemple, CounterStrike, Autodesk, Xrp, Foxtel, Rottentomatoes, Sumologic, Harbor, Dell,
        Discogs, Imdb, Mtr, Pleroma, Jquery, Topcoder, Minds, Jest, Elasticsearch, Reactos, Lua,
        Workplace, Phabricator, Javascript, Openbsd, Fidoalliance, Elastic, Picpay, ReplDotIt,
        Envato, Apachepulsar, Sprint, Anydesk, Gumtree, Shikimori, Microstrategy, Symantec,
        ProtocolsDotIo, Bose, Visualstudio, Angularuniversal, Snapcraft, Textpattern, Fujifilm,
        _1001tracklists, Ebay, Niconico, Gnuicecat, Adobelightroom, Katana, Oyo, Cesium, Windows95,
        Vercel, Opera, Staticman, Abbvie, Cmake, Goldenline, Aeromexico, Dior, Smartthings,
        Barclays, CondaForge, Mariadbfoundation, Metrodeparis, Elasticstack, Hackhands, Musescore,
        Upwork, Gatsby, Adonisjs, Monzo, Adobephonegap, Headspace, DigiKeyelectronics, Xampp,
        Bbciplayer, Apachekylin, Cucumber, Statamic, PreCommit, Smrt, Pycharm, Simpleicons, Dazn,
        Freecodecamp, Tide, Firefox, GogDotCom, NodeRed, Vine, Dsautomobiles, Futurelearn, Houzz,
        Jameson, Fastly, Nec, Quest, Microsoftoutlook, Curl, Mocha, Laravel, Zendesk, Statuspal,
        Shanghaimetro, Miro, Quickbooks, Hipchat, Ubuntu, Icloud, Lgtm, Playstation2, Newrelic,
        Bata, Mta, Kia, Allocine, Cycling74, Thewashingtonpost, XDotOrg, Aeroflot, Known, Crowdin,
        Protonmail, Ring, Runkit, Deviantart, Devrant, Wetransfer, Affinity, V, Dogecoin, Delphi,
        Tmux, Linewebtoon, Cplusplus, Alitalia, Stackshare, Googlemessages, Electron, Airtable,
        Microsoftexchange, Sahibinden, Tui, Blender, Amazonlumberyard, Feathub, Icomoon, Emby,
        Cinema4d, Maytag, Teamspeak, Theregister, Gridsome, ProtoDotIo, Ibeacon, NodeDotJs,
        Wakatime, Pexels, Redbubble, Openstack, XPack, Helpdesk, Nfc, Swarm, Fing, Microgenetics,
        HiveBlockchain, Acm, Photocrowd, Datadog, Sap, Postman, Blazor, Adobelightroomclassic,
        Drooble, Dassaultsystemes, Css3, Analogue, Protonvpn, Quasar, Nuget, Loop, Subaru,
        Openbugbounty, Andela, Pypi, Googledrive, Iobroker, Gitkraken, NextDotJs, Googleclassroom,
        Roamresearch, Express, Adobefonts, Trakt, Consul, Castro, Unsplash, Metafilter,
        Affinityphoto, Reddit, Intercom, Apachesolr, Vapor, Apacheopenoffice, Acer, Yandex,
        Daserste, Shenzhenmetro, Midi, Mdnwebdocs, Embarcadero, Ublockorigin, Tinyletter, Sketchfab,
        Citroen, Bitrise, Gitter, HandshakeProtocol, Saucelabs, Epel, Roundcube, Googleoptimize,
        Buymeacoffee, Kitsu, Showtime, Wattpad, Matomo, Adobeacrobatreader,
        Opencontainersinitiative, Anchor, Piwigo, Majorleaguehacking, Prezi, Rootssage,
        Wikimediacommons, Nba, Puppeteer, Pokemon, Eventbrite, ZWave, Google, Civicrm, Trulia,
        Coveralls, Codeclimate, Hibernate, Beatsbydre, Chinaeasternairlines, Lubuntu, Progress,
        Makerbot, Bmcsoftware, Retropie, Googlephotos, Cachet, Bootstrap, Aerospike, Maas, Spectrum,
        Gulp, Appletv, Fitbit, Skypeforbusiness, Eslgaming, Grunt, Peloton, Saopaulometro,
        Dependabot, Googlemeet, Codingninjas, NewjapanproWrestling, Streamlit, Reactrouter, Aral,
        Qemu, Hubspot, Zoom, Typescript, YourtravelDotTv, Playerfm, Speakerdeck, FDroid, Netflix,
        Googleplay, Ripple, Blackberry, Dynatrace, Thesoundsresource, Autotask, EclipsevertDotX,
        Houdini, Momenteo, Symfony, Eyeem, Themighty, RevealDotJs, Coursera, Zapier, Sellfy, Twilio,
        Onstar, Evernote, TMobile, Pjsip, Gitlfs, Scopus, Bitwarden, Claris, Handshake, Anilist,
        Kibana, Twoo, Vodafone, Openlayers, Codeproject, Azurefunctions, Transferwise, Lmms,
        Abletonlive, Hurriyetemlak, Apollographql, Furrynetwork, Jetbrains, Surveymonkey, Spdx,
        Googlecolab, Bilibili, Eljueves, Iconfinder, Ghostery, Koding, Accusoft, Eagle, Tails,
        Egghead, Googlechat, Microbit, Airbus, Daimler, Soundcloud, Invision, Googlenearby,
        Codersrank, Spinnaker, Samsung, FSecure, Nim, Codepen, Manjaro, Unraid, Redwoodjs,
        Alfaromeo, Openai, Realm, Linuxmint, Wemo, Uber, Xcode, Sky, Alibabacloud, Postgresql,
        DevDotTo, Pingdom, Hackster, Sencha, Revue, Vivaldi, DiagramsDotNet, Homeassistant,
        Nationalgrid, Aircall, Gnuemacs, Kaspersky, Jellyfin, Tinder, Aerlingus, Gitea, Chartmogul,
        Sentry, Fathom, Yoast, Apachedruid, Yamahamotorcorporation, Prismic, Mysql, Bamboo,
        Webdriverio, Postcss, Nativescript, Tile, Opencv, Lighthouse, Stmicroelectronics, Line,
        Codeberg, Snapchat, Tencentqq, Applearcade, Webpack, Ea, Sparkar, Opensourceinitiative,
        Youtubetv, Zotero, Bitdefender, Nintendo3ds, Lydia, Rust, Wheniwork, Cookiecutter,
        Apachecordova, Wikiquote, Audacity, Mix, Eleventy, Couchbase, Erlang, Wipro, Codesandbox,
        Rewe, Gatling, Magisk, Buildkite, Androidauto, Affinitydesigner, Plotly, Googlecardboard,
        Musicbrainz, Cocos, Dunked, LibrariesDotIo, Qatarairways, Aircanada, Toptal, Tensorflow,
        Hackerone, Alliedmodders, MaxPlanckGesellschaft, Vuetify, Pcgamingwiki, Youtubegaming,
        Carthrottle, Adobe, Concourse, Blueprint, C, Dribbble, Netlify, Monkeytie, Infiniti,
        Inkscape, Terraform, Yarn, Ubereats, D3DotJs, Macos, Infosys, Pivotaltracker, Airplayaudio,
        Ionic, Plurk, Mixcloud, Zenn, Shotcut, Archiveofourown, R, RollupDotJs, Swift, Wpengine,
        Mclaren, Zulip, Zorin, Zomato, Ram, Airasia, Retroarch, Cloud66, Webauthn, Googledomains,
        Mitsubishi, Mojangstudios, BAndRautomation, Fite, PlayerDotMe, Quicktime, Insomnia, Udacity,
        BlockchainDotCom, Emlakjet, Periscope, Rtlzwei, Yale, Overcast, Nounproject, Delonghi,
        Rakuten, Mapbox, Discourse, Maserati, Cliqz, Observable, Bugatti, Tailwindcss, Vulkan,
        Wechat, Chupachups, Monster, Taobao, Zillow, Bbc, Microsoftoffice, Stylelint, Thymeleaf,
        ItchDotIo, Stencyl, Jbl, Authy, Zalando, Livestream, Viber, Sonarlint, Kickstarter,
        Generalmotors, Zoho, Meetup, Whatsapp, Coderwall, Codechef, Sonarsource, Fossilscm,
        Academia, Sharp, Solidity, Furaffinity, Wiiu, Scania, Pixabay, Vauxhall, Ikea, Tele5,
        Coffeescript, Designernews, Bigcommerce, Elixir, Razer, Xsplit, Unrealengine, P5DotJs,
        Yamahacorporation, Leetcode, Ovh, Codecademy, Riotgames, Paloaltosoftware, Checkmarx, Rtl,
        Cpanel, Britishairways, Windows, Serverfault, Hitachi, Nintendo, Landrover, Bigbasket,
        Thespritersresource, Instacart, Pantheon, Playstation4, Apacheairflow, Robotframework,
        Bitbucket, Affinitypublisher, Zhihu, Woocommerce, Obsstudio, Suse, Sega, Plesk, Bandlab,
        Knowledgebase, CoOp, Hoppscotch, Arlo, Adobepremierepro, Slides, Webrtc, Semanticweb,
        Matternet, Treyarch, Wikidata, Xfce, Grammarly, V8, Scaleway, Canva, Mozilla, Php, Rstudio,
        Redux, Hilton, Graylog, Testinglibrary, Baremetrics, Neovim, Microsoftvisio, Boeing,
        Esphome, Buefy, Hexo, Jinja, Csharp, Flathub, Monero, Keybase, Exercism, Arxiv, Salesforce,
        Hcl, Dialogflow, Fujitsu, Patreon, Ngrok, Iveco, Metro, TsNode, Apacheant, Renault, Amul,
        Cloudways, Vivino, Steemit, Jaguar, Phpstorm, Evry, Intellijidea, Sfml, Redhatopenshift,
        Orcid, Bugsnag, Nano, MicroDotBlog, Applepay, Vonage, Diaspora, Android, Chevrolet,
        Namebase, Mcdonalds, Storybook, Grav, Openid, Monogram, Johndeere, Cbs, Owasp,
        MobxStateTree, Dlna, Supabase, Whitesource, Java, Zelle, Livechat, Todoist, Espressif,
        Slideshare, Bosch, Hungryjacks, Googlepay, Waze, HotelsDotCom, Virb, Qubesos,
        Adobecreativecloud, Microsoftexcel, Mathworks, Netapp, Moscowmetro, Jrgroup, Qzone,
        Codeship, Lyft, Medium, Apachemaven, Quantcast, Webflow, Gofundme, Pocketcasts, Raspberrypi,
        Unitedairlines, Oracle, Lbry, Telegram, Airplayvideo, Timescale,
        Sanfranciscomunicipalrailway, Pagerduty, Graphcool, Signal, Ssrn, Smashingmagazine, Bt,
        Abbrobotstudio, Gentoo, Threema, Googlescholar, Toyota, Gauges, Facepunch, Xero, Man, Roku,
        Goodreads, Nintendonetwork, Pagekit, Codemagic, Xilinx, Eslint, Icq, Bitwig, Pug, Untappd,
        Qi, Helm, Libuv, Pubmed, Thinkpad, Fandango, Wwe, Transportforlondon, Ifixit, Bigcartel,
        Nrwl, Googlestreetview, Html5, AtAndT, Brandfolder, Uplabs, Auth0, FreedesktopDotOrg, Klm,
        Applemusic, Steam, Mini, Reverbnation, Lichess, Mazda, Fortran, Rss, Vimeo, Googlechrome,
        Verizon, Bitly, Amazonprime, Datastax, Hockeyapp, Renovatebot, Creativecommons, Notist,
        Statuspage, Windowsxp, Foursquare, Douban, Newyorktimes, Slack, Polymerproject,
        Adobeillustrator, Facebooklive, Origin, Deepin, Marketo, Photobucket, Theconversation,
        Sogou, Freebsd, Pepsi, Dailymotion, Aseprite, Castbox, Jsfiddle, Gradle, Rubyonrails,
        Apachegroovy, Apachecassandra, Semver, Discover, Producthunt, Khronosgroup, Ibmwatson,
        Amazonpay, Hulu, Sennheiser, PicartoDotTv, Peugeot, Tasmota, Renren, Lufthansa, Powers,
        Atom, Ticketmaster, Paypal, Lenovo, Faceit, Spyderide, Eclipseche, Songkick, Reasonstudios,
        Circleci, Greensock, Prometheus, Undertale, Publons, Sitepoint, Jupyter, Basecamp,
        Guangzhoumetro, Aurelia, Hackclub, Stackoverflow, Svg, Ieee, Tryhackme, Pegasusairlines,
        Bathasu, Clubhouse, Webmin, Youtubemusic, Tesla, Checkio, Sourceforge, Internetexplorer,
        Stitcher, Quantconnect, Typo3, Gnusocial, Wikivoyage, Deliveroo, Cairometro, Superuser,
        ScikitLearn, Elm, Looker, Fortinet, Amazondynamodb, FerrarinDotVDot, Pioneerdj,
        Googleanalytics, _42, Virustotal, Vmware, DotNet, Pelican, Duckduckgo, Teradata, Indeed,
        Tata, Torbrowser, Suckless, Redis, Googlefit, Overleaf, Powerbi, Okta, Apachespark, Itunes,
        Conekta, Smart, ReduxSaga, Pypy, Klook, Jsdelivr, Yelp, Purescript, Gutenberg, MailDotRu,
        Angular, Linux, Chase, Edx, Framer, Umbraco, Rootsbedrock, Kakao, Laravelhorizon,
        Singlestore, Wire, Pixiv, Volkswagen, Peertube, PiHole, Daf, Samsungpay, Nextdoor, Issuu,
        Drupal, Gerrit, Spotlight, Apple, Vsco, Sparkfun, Trello, SemanticRelease, Jamboard, First,
        Matrix, Vk, Stylus, Cirrusci, Kasasmart, Motorola, Bancontact, Aparat, React, Lastpass,
        Katacoda, Emirates, Readthedocs, Linkedin, Litecoin, Gnuprivacyguard, Aol, Nbb,
        Zendframework, Cnn, Mattermost, Dcentertainment, Bluetooth, Fedora, Accenture, Twitter,
        Plangrid, Wprocket, Codefactor, Expo, Microsoftsqlserver, Protondb, Qualtrics, Pinterest,
        Audible, Laragon, Selenium, Nubank, Trainerroad, Compropago, Kaios, Porsche,
        Openapiinitiative, Celery, Babel, Ideal, Easyjet, Khanacademy, Shell, ParseDotLy, Hive,
        AboutDotMe, Roots, Wikipedia, Youtubestudio, Microsoftpowerpoint, Influxdb, Radar,
        Autohotkey, Openaigym, Humblebundle, Logstash, Kentico, Virtualbox, Postmates, Lionair,
        Archlinux, Opsgenie, Freelancer, Vbulletin, Groupon, Homeassistantcommunitystore, Keras,
        Googlenews, Hey, Klout, _3m, Adguard, Jira, Formstack, Zend, Letsencrypt, Bitcoincash,
        Semaphoreci, Styleshare, Foodpanda, Rancher, Svelte, Thunderbird, Ups, Bitcoinsv, Progate,
        Untangle, Aidungeon, Cockroachlabs, Opencollective, Bmw, Wagtail, Liberapay,
        Materialdesignicons, Moleculer, Highly, Nuke, Safari, Codacy, Firebase, Dashlane, Zdf,
        Fossa, Figma, Expertsexchange, Puppet, Tokyometro, Quip, Curseforge, Adblock, Ghost,
        Youtube, Phonepe, Huawei, EmberDotJs, Iconjar, Latex, Mendeley, Glassdoor,
        Googlesearchconsole, MaterialUi, Apachetomcat, Starship, Caterpillar, Amazonalexa, Osano,
        Adobexd, Linktree, Modx, Windowsterminal, Bugcrowd, Marriott, Adobeindesign, Wizzair,
        Starlingbank, Zoiper, WeightsAndBiases, Logitech, Subversion, Assemblyscript, Dhl, Gamejolt,
        Materialdesign, Openstreetmap, DraugiemDotLv, Azuredevops, Notion, Dolby, Adobephotoshop,
        Rider, Airchina, Arduino, Sourcegraph, Teespring, AlibabaDotCom, Arkecosystem, Prettier,
        Woo, Lg, Badgr, _500px, Fandom, Badoo, Clockify, Internetarchive, Squareenix, Krita,
        Webassembly, Feedly, Tryitonline, Mobx, Deepnote, Webgl, Mastercard, Stadia, Neo4j, Byte,
        Xaml, Jcb, Googlecloud, Jirasoftware, Eclipsemosquitto, Flickr, Twitch, Blogger, Platzi,
        Firefoxbrowser, SocketDotIo, Packagist, Audioboom, Radiopublic, Apachekafka, Githubsponsors,
        Hackerearth, Bunq, Gitee, Komoot, Justgiving, Keycdn, Deutschebank, Zeromq, Flipkart,
        Eventstore, Fastapi, Databricks, Bing, Yammer, Facebook, Square, Castorama, Applepodcasts,
        Nissan, Shopify, Disqus, Amazonaws, Stackpath, Acclaim, Json, Codeforces, Appstore, Zerply,
        Element, Theirishtimes, Egnyte, Pluscodes, Pluralsight, Letterboxd, Trustpilot, Asciinema,
        Chef, Flask, Kahoot, Awsamplify, Rhinoceros, Sonos, Kotlin, Qiwi, Fedex, Derspiegel,
        Staffbase, Geeksforgeeks, Vox, Tripadvisor, Centos, Microsoftonenote, Chinasouthernairlines,
        Myob, Imgur, Qt, Generalelectric, Picnic, Xdadevelopers, Docker, Vaadin, Addthis, Hashnode,
        Adobedreamweaver, Androidstudio, Crehana, Teratail, Codecov, Googlecalendar, Openbadges,
        Nodemon, Bandcamp, Gnome, Saltstack, Tidal, Codio, Osmc, Gravatar, Playstation, Jenkinsx,
        Sonarqube, Wistia, Icon, Angularjs, Yahoo, Breaker, Ifood, Hackaday, Flattr, Startrek,
        RollsRoyce, PopOs, Metrodemadrid, Elasticcloud, Googlecast, Beatport, Numba, Clickup, Ansys,
        Broadcom, Metrodelaciudaddemexico, Fiverr, Microsoftazure, Audiomack, Glitch, Hp,
        Resurrectionremixos, Udemy, Fila, Messenger, Bankofamerica, Nokia, Cisco, Slackware,
        Fluentd, Fnac, Apacherocketmq, Behance, Steem, Talend, Powershell, Meteor, Quarkus,
        Society6, Microsoftaccess, Tvtime, Sketch, Zigbee, Apacheecharts, Ardour, DWavesystems,
        Ycombinator, Tableau, Bulma, Quantopian, Buzzfeed, Codingame, Apachejmeter, Homebrew,
        Aiohttp, Stubhub, Usps, Symphony, Opel, Apachenetbeanside, Cognizant, Hyundai, N26, Ford,
        Plex, Wish, Scala, Tutanota, Renpy, Cashapp, Vfairs, Activision, Steinberg, Microsoftteams,
        Amp, Fastify, Naver, Codeigniter, Scrutinizerci, Go, Presto, Kaggle, Htmlacademy, TpLink,
        Libreoffice, Fifa, Bandsintown, Runkeeper, Lumen, Dwm, Wireshark, Googleassistant, Steamdb,
        Spacemacs, Invoiceninja, Pinboard, Ana, Launchpad, Oshkosh, Premierleague, Oneplus, Fiat,
        Teamviewer, Uploaded, Stripe, Screencastify, Instagram, Cloudcannon, Linode, Octave,
        Kongregate, Cdprojekt, Ted, Asus, Wordpress, Truenas, Sonicwall, Googletranslate, Slashdot,
        Microsoftsharepoint, Debian, Nestjs, Django, Oxygen, Vectorlogozone, Reason, Jekyll,
        Empirekred, Notepadplusplus, Informatica, Lospec, Pfsense, Instapaper, Torproject, Kofax,
        Spring, Gnu, _1password, Kalilinux, Angellist, Playstation5, Docusign, _4d, Swiggy,
        Ubiquiti, Instructables, Podcastaddict, Rainmeter, Tencentweibo, Pastebin, Qwiklabs, Xmpp,
        Synology, Integromat, Wix, SatDot1, Lada, WarnerbrosDot, Elementary, Joomla, Toggl,
        Azuredataexplorer, Bit, Azureartifacts, Falcon, G2a, WebcomponentsDotOrg, Sololearn,
        Songoda, Ingress, Homebridge, Ipfs, ShieldsDotIo, Wolframmathematica, Uikit, Grubhub,
        Cypress, Confluence, Hypothesis, Testin, Podman, Nextcloud, Ruby, Composer, Macys, Unilever,
        Fontawesome, Loom, Carto, Lineageos, Kde, Strava, Grafana, Ceph, Jfrog, Visualstudiocode,
        Opengl, Chocolatey, StyledComponents, Flood, ThreeDotJs, Baidu, Pagespeedinsights, Buddy,
        Payoneer, Wappalyzer, Algolia, Substack, AFrame, Manageiq, Reactivex, WriteDotAs, Travisci,
        Etihadairways, Unicode, Unacademy, Webmoney, Seat, Googlemybusiness, VueDotJs, Apacheflink,
        Hellyhansen, Xiaomi, Pocket, Racket, Codeceptjs, Homeadvisor, Googlelens, Git, Magento,
        Less, Wolframlanguage, Hbo, Perl, Snyk, Probot, Bentley, Coronaengine, Crowdsource,
        Ethereum, Ros, Skillshare, Flutter, Fastlane, Mcafee, Dacia, Relianceindustrieslimited,
        Nutanix, Mewe, Github, Awesomewm, Disroot, Kik, Keepassxc, Protools, Awesomelists, Xing,
        Ello, Intel, Planet, Tunein, Redhat, Dynamics365, Librarything, Asciidoctor, Pingup,
        Delicious, Iconify, Americanairlines, Unity, Folium, Myspace, Giphy, Honda, Mailchimp,
        Sefaria, Alipay, Beats, Storify, Cryengine, Aventrix, Jet, Winmate, Sqlite, Vultr,
        Convertio, Everplaces, Cloudera, Azurepipelines, Atari, Gitpod, Genius, Epicgames, Archicad,
        Cloudflare, Tomorrowland, Tiktok, Markdown, Splunk, Vault, Nucleo, Crystal, Googlepodcasts,
        Boost, Appsignal, Moo, Flipboard, Countingworkspro, Triller, Solus
    }
}