package packs

import compose.icons.AllIcons
import compose.icons.TablerIcons
import compose.icons.tablericons.BrandTabler

class Tabler {
    companion object : IconPack {
        override val name: String = TablerIcons::class.simpleName!!
        private val all = "" to Icons.entries
        override val packs = mapOf(all)
        override val icons = TablerIcons.AllIcons
        override val icon = TablerIcons.BrandTabler
    }

    enum class Icons {
        CalendarTime, ThumbUp, TextWrap, Car, DropletFilled, LetterE, Template,
        UserCheck, Location, AlignLeft, MoodBoy, LetterA, Train, Columns, ZodiacLibra, Atom2, Woman,
        BrandTiktok, Coin, LivePhoto, Underline, CurrencyNaira, BoxPadding, LayoutGridAdd,
        Biohazard, DeviceGamepad, Map2, Headset, CaretLeft, StepInto, CornerLeftUpDouble,
        HexagonOff, Brackets, CurrencyRupee, LayersIntersect, ListCheck, MessageOff, GitMerge,
        BoxMultiple0, CurrencyRubel, BellRinging, Camera, ArrowsJoin2, ShieldOff, ScooterElectric,
        ArrowDownRight, CircleOff, ArrowNarrowLeft, TextDirectionLtr, Outlet, TruckDelivery, H6,
        Replace, BrandCss3, Drone, FileDownload, Number0, UserExclamation, PhoneOff, ArrowBarUp,
        SortDescending, HandThreeFingers, BrandSkype, ReportMoney, BoxMultiple4, Shape3, BrandAsana,
        CurrencyLeu, Temperature, FileOff, BrightnessDown, Plus, Exchange, CurrencyForint,
        SquareToggleHorizontal, Wifi1, Minus, Binary, ZoomCheck, MoodConfuzed, Trademark,
        ChartArrows, Percentage, Speakerphone, Backspace, Upload, ColumnInsertRight,
        ShoppingCartPlus, Speedboat, Plane, LetterCase, ArrowRampRight, Circle1, Forbid2,
        BrandTidal, BrandProducthunt, Notebook, LoaderQuarter, CurrencyPound, Moped,
        LayoutAlignLeft, DeviceAnalytics, Divide, GitCommit, CurrencyYen, ChartDonut2, Tallymark1,
        HandStop, CodePlus, BrightnessHalf, ArrowLoopRight, ArrowRightSquare, CurrencyReal, GitFork,
        Bandage, CornerLeftDownDouble, BrandTelegram, AccessPoint, GitBranch, Direction, BorderTop,
        MoodTongue, FileCode, BrandBehance, DeviceMobileMessage, CircleDashed, Gauge,
        CornerDownLeft, Number2, Container, ArrowsDiagonal, BrandChrome, Battery3, FoldUp, Trident,
        ArrowsVertical, Square6, DirectionHorizontal, CornerUpRight, BrandSteam, ArrowTopTail,
        ArrowTopBar, ChevronsRight, Square1, _3dCubeSphere, SmartHome, DotsDiagonal2, CircleDotted,
        ArrowsDoubleNeSw, Ruler2, PictureInPicture, ChevronsUpLeft, Maximize, LetterD, Refresh,
        BrandDiscord, Physotherapist, ArrowForward, WaveSine, Box, FileCode2, GripVertical,
        BrandHipchat, CurrencyZloty, FileInfo, Snowflake, ArrowBarToDown, BoxModel, ArrowUp,
        DeviceTablet, MoodSmile, PlaneDeparture, ArrowLeftSquare, BuildingSkyscraper,
        BatteryCharging, ZoomOut, Alarm, BrandTailwind, Wand, Router, Circle, Tank,
        LetterCaseToggle, Aperture, BallFootballOff, FlipHorizontal, ZoomIn, ArrowDownLeftCircle,
        Shredder, DropletOff, ChevronDown, Alien, Tools, FileDislike, LineDotted, CloudDownload,
        LayoutAlignCenter, BrandMedium, CircleMinus, ArrowLeftTail, BrandOpera, BrandGooglePlay,
        ArrowBottomBar, LayoutDistributeVertical, Truck, ArrowBarDown, Code, BuildingCommunity,
        RecordMail, Recharging, Backhoe, ChartArea, RelationOneToOne, CornerRightUp, ArrowsMaximize,
        Fall, DeviceMobileRotated, ArrowBigLeft, ChartInfographic, Registered, Palette, ZodiacAries,
        Package, LayoutDistributeHorizontal, Ruler, Circle3, CameraRotate, Target, History,
        CloudFog, ChargingPile, SeparatorHorizontal, LockAccess, ChevronsUpRight, Home,
        BrandCodesandbox, Stethoscope, Stairs, ArrowsUpDown, Sailboat, Fold, Point,
        BuildingHospital, InfoCircle, Artboard, VideoMinus, Diamond, Checks, Parentheses,
        ReportAnalytics, Golf, Businessplan, FileAlert, ArrowsLeftDown, CameraPlus, JumpRope,
        BluetoothConnected, AlignJustified, ArrowLeftCircle, ChartPie, FileShredder, BrandTwitch,
        RadiusTopRight, BrandTumblr, Bucket, Pyramid, Database, AB, TruckReturn, Printer, Pray,
        Moon, Stack, ChartDonut3, ArrowLeftBar, BellOff, Wifi0, ChartBar, ChevronsDown, H4,
        ZodiacVirgo, Wallet, Message, MapPins, LetterM, Overline, BuildingWarehouse, Clock,
        Brightness2, ShoppingCartX, SquareRotatedOff, BrandBitbucket, HandRingFinger, LayoutCards,
        UserMinus, Circle8, Submarine, Copyleft, News, LetterT, ZodiacPisces, HandLittleFinger,
        Parking, BrandHtml5, CurrencyBath, ArrowUpLeft, BrandDeviantart, LetterZ, Bed,
        ArrowsDoubleSwNe, TableImport, SquareOff, BuildingFactory, Heading, Signature, LetterW,
        BorderHorizontal, ArrowUpRight, DropletHalf, Windmill, BookmarkOff, Ban, Shield, Tent,
        KeyboardHide, StairsDown, ZodiacGemini, Crown, BrandFlickr, Crosshair, VectorBeizer, Comet,
        QuestionMark, Ad, ArrowWaveLeftDown, Mars, WaveSquare, Award, DeviceFloppy, FileUpload,
        AlignCenter, ColorSwatch, BrandVimeo, FileX, SquareRotated, RoadSign, BrandPinterest,
        Plant2, BrandApple, Disabled2, FileSearch, Nfc, ArrowNarrowRight, Ambulance, FileSymlink,
        Discount2, BrandGoogleAnalytics, ArrowsHorizontal, LetterY, LetterCaseUpper, LetterH,
        ArrowsUpLeft, ArrowBack, Settings, Moon2, PhoneCalling, LayoutAlignBottom, Rectangle,
        ToggleRight, Presentation, LetterO, Directions, Triangle, Shape, Click, Rotate2, Glass,
        EyeCheck, FileReport, DeviceSpeaker, BuildingChurch, List, ClipboardX, Section, Phone,
        LineDashed, Slice, Marquee, Route, Users, AntennaBars3, Anchor, MoodSuprised, Flag, Trophy,
        Italic, NewSection, CurrencyDollarSingapore, Parachute, Pokeball, ShadowOff, CurrencyShekel,
        ArrowsSort, PlayerPlay, BallVolleyball, CircleCheck, LayoutGrid, Hexagon, Notification,
        BrandSoundcloud, Puzzle, ScreenShareOff, Bug, CornerDownRight, Terminal, LayoutSidebar,
        Helicopter, PhonePlus, BallBasketball, Pencil, FilePhone, CurlyLoop, SquareRoot, ToggleLeft,
        LetterL, EditCircle, BrandPatreon, Battery4, PlayerStop, LetterS, SortAscending2,
        BuildingStore, Affiliate, BellMinus, FloatCenter, Tir, Ripple, LayoutRows, ChartDonut,
        AerialLift, Karate, CurrencyRiyal, Edit, UserPlus, BrandGitlab, BoxMultiple1, Lifebuoy,
        ChartBubble, DeviceMobile, BorderAll, ArrowLeft, Square9, CashBanknote, Layout, PhoneX,
        BallTennis, HandRock, DevicesPc, Plug, CurrencyKroneSwedish, Disc, BrandWhatsapp, ArrowDown,
        Lego, PresentationAnalytics, IndentDecrease, LetterQ, Login, Number1, ClipboardCheck,
        ArrowTopSquare, ArrowLoopLeft, Servicemark, Hierarchy2, TestPipe, Math, Number5, Square4,
        Square0, Polaroid, BorderVertical, LineHeight, WifiOff, CirclePlus, Separator, UserX,
        BoltOff, Eye, Recycle, TrendingUp2, PhoneCheck, Scissors, Egg, ArrowsSplit2, BuildingBank,
        Typography, Propeller, Briefcase, BoxMargin, Movie, ChevronUpLeft, Massage, Files, Braces,
        Checkbox, ClearAll, Superscript, BrandEdge, Selector, Line, Scan, ViewportWide, LetterF,
        DatabaseImport, ArrowUpCircle, ZodiacCancer, Basket, Capture, Sum, ChevronsLeft,
        ArrowForwardUp, Sun, CornerRightUpDouble, Hanger, AntennaBars1, BrandDisqus, DropletHalf2,
        LetterX, Run, Send, Battery, CornerRightDown, DeviceAudioTape, Virus, Select, GitCompare,
        StepOut, ReceiptTax, PhoneOutgoing, Circle9, SquaresDiagonal, FlipVertical, SunOff,
        ChartArcs3, Flame, Pinned, TrendingDown3, LayoutAlignTop, Video, TextDirectionRtl, Emphasis,
        Strikethrough, ShoppingCartOff, FileExport, ZodiacCapricorn, ShieldX, Perspective, FaceId,
        FolderMinus, LayoutAlignRight, Circle4, ChevronUpRight, Rainbow, Folders, PhotoOff,
        LayersLinked, FileAnalytics, DatabaseOff, BrandSentry, Peace, Ear, BoxMultiple7, Rocket,
        ArrowBackUp, Circle0, CornerUpLeftDouble, SquareCheck, BorderStyle, ArrowsMinimize, Circle2,
        ArrowBigRight, MailOpened, MessageCircle, PlayCard, DeviceDesktopOff, ReceiptOff, MoodKid,
        SquareForbid, Subscript, Circles, ViewportNarrow, WritingSign, TiltShift, Skateboard,
        SwitchVertical, Leaf, RotateClockwise2, Menu, Home2, ArrowBigDown, BrandWindows, Circle7,
        MessageReport, Stars, CornerLeftUp, Medal, BallFootball, BrandNetflix, Fingerprint,
        Paperclip, ArrowBottomTail, ToolsKitchen2, Flare, Bulldozer, SquarePlus, BrandAppstore,
        _2fa, DragDrop2, Adjustments, MapPinOff, Crop, Brightness, SquareForbid2, ArrowRightCircle,
        CodeMinus, Volume, LayoutKanban, BellPlus, AdjustmentsHorizontal, OctagonOff, BorderRight,
        BrandGoogleDrive, CornerUpRightDouble, Tool, ArrowsRightDown, Cut, LetterJ, PlayerTrackNext,
        EyeOff, RotateClockwise, Tag, PlayerPause, BatteryOff, BorderLeft, DropletFilled2,
        ChartPie2, Report, Clipboard, Sitemap, SportBillard, ArrowsDownUp, File, CurrencyRipple,
        Pizza, RepeatOnce, Tallymark3, BrandSlack, Switch2, MathFunction, ZoomMoney, Book,
        Cardboards, RotateRectangle, Building, BuildingCottage, BluetoothOff, ChartArrowsVertical,
        LetterCaseLower, ArrowBarToRight, Ship, CornerRightDownDouble, HeartBroken, H2, FloatRight,
        FileDiff, TextWrapDisabled, BrandAppleArcade, ArrowsUpRight, CalendarMinus, BoxMultiple9,
        BrandDocker, Square3, Check, Globe, SquareX, MedicalCross, TrafficLights, BrandPocket,
        Server, Discount, Blockquote, Man, MaskOff, Bone, ChevronsUp, CurrencyBitcoin,
        HelicopterLanding, Infinity, LetterR, ArrowRightBar, PlaneArrival, ChevronUp, Sunset,
        BellRinging2, Forbid, BellX, Tallymarks, VideoPlus, BoxMultiple6, VirusOff,
        BuildingFortress, VideoOff, BrandSnapchat, ArrowUpRightCircle, ScreenShare, ColorPicker,
        Rss, ArrowDownRightCircle, ArrowBigTop, BrandDribbble, FloatNone, ArrowsDown, Square2,
        BrandSafari, ChevronDownRight, FolderOff, Venus, Square8, Square5, Eyeglass, Loader,
        AlignRight, Copyright, BuildingBridge, ChartPie3, ZoomQuestion, Flag3, BrandTabler, Smoking,
        Microphone, TrendingDown2, ZodiacLeo, BrandYcombinator, Bus, World, CalendarStats, Tractor,
        BrandBing, Number8, Omega, RadiusBottomRight, VectorBeizer2, Atom, MoodCrazyHappy,
        SquareDot, BorderBottom, ChartLine, BorderInner, ArrowUpLeftCircle, Prompt, BoxMultiple,
        ArrowTopCircle, HeadphonesOff, MessageCircle2, Menu2, LayoutAlignMiddle, Writing, Copy,
        Wind, GlassFull, CashBanknoteOff, Rotate, ArrowsRight, CurrencyBahraini, DotsDiagonal,
        FilePlus, DeviceTv, Logout, CurrencyDinar, ArrowBottomCircle, ChartAreaLine, DeviceWatch,
        BrandReddit, BrandFramer, CreditCardOff, PlayerRecord, LayersUnion, WaveSawTool, CaretDown,
        CurrencyDollar, IceCream, Gift, YinYang, Pacman, Shirt, Calendar, FileZip, Number4,
        MicrophoneOff, TableOff, View360, Tallymark4, Square7, CameraOff, PlayerSkipBack, Frame,
        Olympics, CornerDownRightDouble, Hierarchy, TemperatureMinus, LockOpen, Id, BoxMultiple3,
        BrandBooking, Focus, Music, Geometry, WiperWash, AdjustmentsAlt, Versions, FloatLeft,
        FileMusic, BrandKotlin, DatabaseExport, ZodiacScorpio, Filter, Motorbike, FilterOff,
        BrandGravatar, ZodiacTaurus, Search, Activity, Folder, TriangleOff, Dimensions, Bluetooth,
        Bookmark, PictureInPictureOff, Dna, CurrencyDirham, LayoutColumns, PlayerSkipForward,
        BoxMultiple2, Trash, StairsUp, Number7, PinnedOff, CurrencyKroneCzech, DeviceCctv, Devices2,
        CaretRight, CircleX, Help, ArrowNarrowDown, Umbrella, BrandCodepen, Magnet, Key, License,
        Certificate, BulbOff, TrafficCone, ChevronsDownRight, X, BrandUnsplash, Sock, Circle6,
        ArrowRight, IndentIncrease, Details, ArrowBottomSquare, FolderX, AlertCircle, Wifi,
        ArrowsLeft, Power, Satellite, Viewfinder, DroneOff, ArrowBarRight, Headphones, MoodNeutral,
        LiveView, MinusVertical, Messages, RelationManyToMany, Forms, Accessible, BuildingMonument,
        ThumbDown, Mist, CircleHalf, LetterU, StarHalf, Resize, ArrowBarToLeft, DragDrop,
        CurrencyKroneDanish, ExternalLink, CircleSquare, AlertTriangle, BatteryAutomotive, Ghost,
        Shape2, AspectRatio, Calculator, Old, Sunshine, DotsCircleHorizontal, SteeringWheel,
        SmokingNo, AccessPointOff, ChartCandle, Command, WreckingBall, Track, MoodSad, GasStation,
        CurrentLocation, Disabled, ArrowDownCircle, Download, ArrowsSplit, Seeding, CurrencyEuro,
        SquareToggle, Switch, Wiper, Forklift, Ce, School, ZodiacSagittarius, LayoutBottombar,
        ScubaMask, BrandSpotify, Number9, Language, CurrencyDollarCanadian, Equal, Link, ArrowsUp,
        SettingsAutomation, HandFinger, Keyboard, ReportMedical, AntennaBars4, ChevronDownLeft,
        ChartArcs, CurrencyLira, ReceiptRefund, Mailbox, DeviceDesktopAnalytics, CameraMinus,
        ChartPie4, PhoneIncoming, ArrowBarLeft, Receipt, StarOff, PlayerTrackPrev, Pool, Bike,
        WorldLatitude, ZodiacAquarius, BrandLinkedin, MessagesOff, CameraSelfie, AntennaBars5,
        Notes, ArrowBarToUp, Message2, Photo, Droplet, RadiusTopLeft, Slideshow, ClearFormatting,
        Map, BrandSass, Circle5, ArrowWaveLeftUp, DotsVertical, Square, BrandFacebook, BorderNone,
        Shadow, Plant, Mouse, Unlink, BrandPagekit, Volume3, ChristmasTree, BrandFoursquare, Vector,
        Dice, BallAmericanFootball, Number3, TrendingDown, LetterC, FileMinus, BuildingPavilon,
        PhonePause, ShieldCheck, Flag2, Flask, CornerUpLeft, MessageDots, CloudOff, BrandSketch,
        BrandStripe, BorderOuter, CalendarPlus, SortAscending, LayoutList, Window, BoxMultiple5,
        Confetti, Star, InfoSquare, FileImport, Gps, SquareMinus, VectorTriangle, Grain,
        PanoramaVertical, PageBreak, Walk, ArrowsJoin, CloudStorm, Mug, ChevronLeft, Terminal2,
        BrandGithub, HandMiddleFinger, Marquee2, Swimming, BrandInstagram, Pennant, LetterV, Macro,
        CurrencyFrank, At, LayersDifference, Urgent, FoldDown, ChevronsDownLeft, BorderRadius,
        TriangleSquareCircle, Hash, Apps, ArrowWaveRightUp, Variable, Inbox, Eyeglass2, FolderPlus,
        BrandTwitter, BoxMultiple8, RelationOneToMany, ArrowNarrowUp, Mail, CrownOff, BrandShazam,
        Repeat, ArrowRampLeft, BrandFirefox, PictureInPictureOn, Dashboard, CircleHalfVertical,
        BrandYoutube, Lock, BrandVk, Feather, BuildingBridge2, Pin, BuildingCastle, Bulb, Share,
        FileText, FileHorizontal, LetterSpacing, MapPin, RadiusBottomLeft, RowInsertBottom,
        MoodHappy, DeviceComputerCameraOff, Scale, CornerLeftDown, LetterN, GlassOff, Pill,
        RectangleVertical, FilesOff, TemperatureCelsius, Compass, CaretUp, MailForward, Bolt,
        CurrencyEthereum, Octagon, Social, Caravan, ArrowsLeftRight, RowInsertTop, DeviceDesktop,
        SoccerField, Scooter, Volume2, Space, KeyboardShow, GridDots, Layout2, RefreshAlert,
        FileInvoice, Tournament, Playlist, BrandAirbnb, LetterG, LettersCase, ManualGearbox, Tree,
        SortDescending2, HandTwoFingers, CurrencyWon, ChartRadar, FileLike, MoodEmpty,
        MessageCircleOff, Stack2, ChartDots, Eraser, Tornado, Contrast, ListSearch, LetterP,
        TrendingUp3, LayoutNavbar, BrandOpenSource, EqualNot, Barcode, CurrencyLitecoin, Friends,
        BrandPaypal, Battery2, ChartCircles, ArrowsRightLeft, Growth, CurrencyTugrik, TableExport,
        Battery1, CloudRain, BrandTinder, Trees, TemperatureFahrenheit, LetterK, ClipboardList,
        BrandPython, Vaccine, Tallymark2, Exposure, DeviceMobileVibration, Qrcode, Receipt2,
        ShoppingCart, ArrowsDoubleNwSe, ToolsKitchen, LetterB, BrandYahoo, MoonStars, AlertOctagon,
        Subtask, CreditCard, PhoneCall, BallBowling, Archive, Bold, MathSymbols, ArrowWaveRightDown,
        TruckOff, H1, Minimize, CurrencyRenminbi, SeparatorVertical, CurrencyCent, CloudUpload,
        BrandMessenger, Number6, BuildingLighthouse, VirusSearch, LayersSubtract, Devices,
        Bookmarks, FileCertificate, Switch3, Ticket, BrandGoogle, CursorText, MessagePlus,
        DeviceLaptop, Firetruck, BrandKickstarter, TrashOff, IceCream2, WorldLongitude,
        ArrowsDiagonal2, DeviceComputerCamera, ChevronRight, Browser, ZoomCancel, SquareRoot2,
        SquaresFilled, Sticker, Focus2, TemperaturePlus, ChartDonut4, Radioactive, Heart, Bell,
        HandOff, LetterI, UserOff, EarOff, AntennaBars2, CurrencyDollarAustralian, Cast,
        ColumnInsertLeft, LockOff, Planet, ArrowDownLeft, SwitchHorizontal, ShieldLock,
        ShoppingCartDiscount, H5, BuildingArch, CloudSnow, BrightnessUp, Wifi2, Cash, H3,
        CalendarEvent, TrendingUp, Brush, CurrencyTaka, GripHorizontal, BrandFigma, Dots, MoodCry,
        ArrowRightTail, Note, Cloud, Paint, KeyboardOff, ArrowsDoubleSeNw, Markdown, GitPullRequest,
        BrandAndroid, CornerDownLeftDouble, BuildingCarousel, PanoramaHorizontal, Table,
        LayoutSidebarRight, FileCheck, User, CalendarOff, Mask
    }
}